[auth]
verifyUrl="http://localhost:8080/auth/api/auth/verify"

[http]
port=44400
publicUrl="http://localhost:8080/notify"

[mongo]
url="mongodb://localhost:27017/notify-development"

[mqtt]
url="mqtt://localhost/"